name: test-workflow
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }}"
      - run: cat <<< "${{ github.event.head_commit.message }}"
      - run: cat <<< "${{ join(github.event.label.*.name, ',') }}"
      - if: |
          ${{ ! contains(github.event.head_commit.message, '[test]') }} &&
          ${{ ! contains(github.event.label.*.name, 'bug') }}
        run: echo "Hello World"
