name: test-workflow
on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.workflow }}"
      - run: cat <<< "${{ github.event.push.head_commit.message }}"
      - run: cat <<< "${{ github.event.head_commit.message }}"
      - run: cat <<< "${{ join(github.event.pull_request.labels.*.name, ',') }}"
      - run: cat <<< "${{ join(github.event.label.*.name, ',') }}"
      - if: |
          ${{ ! contains(github.event.head_commit.message, '[test]') }} &&
          ${{ ! contains(github.event.pull_request.labels.*.name, 'bug') }}
        run: echo "Hello World"
